# Generated by Django 6.1 on 2026-09-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_galleryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
