# Generated by Django 6.1 on 2026-09-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_galleryitem_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='media_file',
            field=models.FileField(default='', upload_to='gallery/'),
            preserve_default=False,
        ),
    ]
