# Generated by Django 6.1 on 2026-09-28 08:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_galleryitem_media_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='experience/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='main.experience')),
            ],
        ),
    ]
